ENTITY INVERSORC2 IS 
	PORT(
		EC21:IN BIT_VECTOR(3 DOWNTO 0);
		nC2E:OUT BIT_VECTOR(3 DOWNTO 0);
	Cout:OUT BIT);
END INVERSORC2;
ARCHITECTURE invertec2 OF INVERSORc2 IS
COMPONENT SOMA4BITS
	PORT(Carryin:IN BIT;
		X1,X2:IN BIT_VECTOR(3 DOWNTO 0);
		Sout:OUT BIT_VECTOR(3 DOWNTO 0);
	Carryout:OUT BIT);
END COMPONENT;
SIGNAL c:BIT_VECTOR(3 DOWNTO 0);
SIGNAL d:BIT_VECTOR(3 DOWNTO 0);
BEGIN
	c(0)<=NOT(EC21(0));
	c(1)<=NOT(EC21(1));
	c(2)<=NOT(EC21(2));
	c(3)<=NOT(EC21(3));
	d(0)<='1';
	d(1)<='0';
	d(2)<='0';
	d(3)<='0';
	Inv:SOMA4BITS PORT MAP(Carryin=>'0',X1=>c,X2=>d,Sout=>nC2E,Carryout=>Cout);
END invertec2;
