ENTITY SOMA1B IS 
PORT(a,b,Cin:IN BIT;
	s,Cout:OUT BIT);
END SOMA1B;
ARCHITECTURE SOMADOR OF SOMA1B IS
BEGIN
s<=(a)XOR(Cin)XOR(b);
Cout<=((a)AND(b))OR((b)AND(Cin))OR((Cin)AND(a));
END SOMADOR;